Vagrant.configure(2) do |config|
  config.vm.define "TeamSpeak" do |ts|
    #Auswahl der Box, der Host Name und Ports Einstellungen der VB
    ts.vm.box = "generic/ubuntu1804"
    ts.vm.hostname = "TeamSpeak"
    ts.vm.network "forwarded_port", guest:22, host:2222, auto_correct: true
    ts.vm.network "forwarded_port", guest:9987, host:9987, auto_correct: true, protocol: "udp"
    ts.vm.network "forwarded_port", guest:30033, host:30033, auto_correct: true, protocol: "tcp"
    ts.vm.network "forwarded_port", guest:10011, host:10011, auto_correct: true, protocol: "tcp"
    ts.vm.network "forwarded_port", guest:41144, host:41144, auto_correct: true, protocol: "tcp"
    #Virtualisierungs Programm, Name und Memory der VM auswählen
    ts.vm.provider "virtualbox" do |vb|
      vb.name = "TeamSpeak-Server"
      vb.memory = "1024"
    end
    #Mit diesem Schritt bringen wir die VM auf den neusten Stand
    ts.vm.provision "shell", inline: <<-SHELL
      #sudo apt-get update
      #sudo apt-get upgrade -y
      #Packet von Teamspeak herunterladen von einer Mirrorseite und dann gleich entpacken
      cd /tmp
      wget http://dl.4players.de/ts/releases/3.6.1/teamspeak3-server_linux_amd64-3.6.1.tar.bz2
      tar -xjf teamspeak3-server_linux_amd64-3.6.1.tar.bz2 -C /usr/local/bin/
      rm teamspeak3-server_linux_amd64-3.6.1.tar.bz2
      cd
      #In das Verzeichnis /usr/local/bin/teamspeak3-server_linux_amd64 wechseln
      cd /usr/local/bin/teamspeak3-server_linux_amd64
      #Vor dem start müssen noch folgende Files von Hand angelegt werden
      sudo ./ts3server createinifile=1
      sudo sed -i 's/license_accepted=0/license_accepted=1/g' /usr/local/bin/teamspeak3-server_linux_amd64/ts3server.ini
      #sudo touch /usr/local/bin/teamspeak3-server_linux_amd64/ts3server_license_accepted
      #Starten des Dienstes bzw. des Servers
      #sudo ./ts3server_startscript.sh start inifile=ts3server.ini
      sudo ./ts3server_startscript.sh start inifile=ts3server.ini
      SHELL
    end
  end
