version: '3.2'
services:
    teamspeak:
        build: .
        command: /start
        ports:
          - "9987:9987/udp"
          - "30033:30033"
          - "10011:10011"
          - "41144:41144"
        environment:
          - TS3SERVER_LICENSE=accept
        volumes:
            - ./
        restart: always
