Vagrant.configure(2) do |config|
  config.vm.define "LogServer" do |ls|
    #Auswahl der Box, der Host Name und Ports Einstellungen der VB
    ls.vm.box = "generic/ubuntu1804"
    ls.vm.hostname = "LogServer"
    ls.vm.network "forwarded_port", guest:80, host:8081, host_ip: "0.0.0.0"
    #Virtualisierungs Programm, Name und Memory der VM auswählen
    ls.vm.provider "virtualbox" do |vb|
      vb.name = "Log-Server"
      vb.memory = "1024"
    end
    #Mit diesem Schritt bringen wir die VM auf den neusten Stand
    ls.vm.provision "shell", inline: <<-SHELL
      sudo useradd -m logadmin -p $(echo "asdf1234" | openssl passwd -1 -stdin)
      sudo usermod -aG sudo logadmin
      echo "vagrant:1234"|chpasswd
      #sudo apt-get update
      #sudo apt-get upgrade -y
      sudo apt-get install ufw -y
      #sudo ufw enable
      #sudo ufw allow from any to any  port 80
      SHELL
      #Nach dem aktualisieren muss die VM reloaded werden,
      #um einen möglichen reboot nach dem aktualisieren durchzuführen
      ls.vm.provision :reload
      ls.vm.provision "shell", inline: <<-SHELL
      #
      sudo apt-get install webalizer -y
      SHELL
    end
end
