#LB01 TeamSpeak Server + Überwachungs Server

#VB Einrichtung
Vagrant.configure(2) do |config|
      #TeamSpeak
      config.vm.define "teamSpeak" do |teamspeak|
      teamspeak.vm.box = "generic/ubuntu1804"
      teamspeak.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
      teamspeak.vm.synced_folder ".", "/var/www/html"

      teamspeak.vm.provider "virtualbox"
      teamspeak.name = "TeamSpeak-Server"
      teamspeak.memory = "512"
    end
  end

      #Ueberwachung
      config.vm.define "Ueberwachung" do |uw|
      uw.vm.box = "generic/ubuntu1804"
      uw.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
      uw.vm.synced_folder ".", "/var/www/html"

      config.vm.define "Ueberwachung" do |ts|

      uw.vm.provider "virtualbox"
      uw.name = "Ueberwachung-Server"
      uw.memory = "512"
    end
  end

#TeamSpeak Installation
#Mit diesem Schritt bringen wir die VM auf den neusten Stand
ts.vm.provision "shell", inline: <<-SHELL
  #Update Packages vom lokalen Server holen
  sudo apt-get update
  sudo apt-get upgrade -y
  SHELL
#Nach dem aktualisieren muss die VM reloaded werden,
#um einen möglichen reboot nach dem aktualisieren durchzuführen
  ts.vm.provision :reload
  ts.vm.provision "shell", inline: <<-SHELL
    #Firwall
    sudo ufw allow 22/tcp
    sudo ufw allow 123/udp
    sudo ufw -f enable
    SHELL
